apiVersion: v1
kind: Service
metadata:
  name: ceph
spec:
  type: ClusterIP
  ports:
  - port: 9000
    targetPort: 9000
    protocol: TCP
  selector:
    app: ceph
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ceph
  labels:
    app: ceph
spec:
  selector:
    matchLabels:
      app: ceph 
  template:
    metadata:
      labels:
        app: ceph
    spec:
      containers:
      - image: ceph/ceph:latest
        name: image
        args:
        - server
        - /data
        env:
        - name: ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: objectstorage-provisioner
              key: ACCESS_KEY
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: objectstorage-provisioner
              key: SECRET_KEY
