apiVersion: v1
kind: Secret
metadata:
  name: objectstorage-provisioner
  labels:
    app.kubernetes.io/part-of: container-object-storage-interface
    app.kubernetes.io/component: driver-ceph
    app.kubernetes.io/version: main
    app.kubernetes.io/name: cosi-driver-ceph
type: Opaque
stringData:
  HOST: "http://rgw:8080"
  ACCESS_KEY: "ceph"
  SECRET_KEY: "ceph123"
